// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADqvda68VWg-JymkKpE6wuJiCD6Avn0C4',
    appId: '1:373667761246:web:e8fafd1ff64eeb720278cf',
    messagingSenderId: '373667761246',
    projectId: 'lab3-mis-62c8f',
    authDomain: 'lab3-mis-62c8f.firebaseapp.com',
    storageBucket: 'lab3-mis-62c8f.firebasestorage.app',
    measurementId: 'G-148PGPSGJJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKdj0RIyrhJFGWnUck1YdEzYN1emBESwo',
    appId: '1:373667761246:android:e940e314c1d755950278cf',
    messagingSenderId: '373667761246',
    projectId: 'lab3-mis-62c8f',
    storageBucket: 'lab3-mis-62c8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcAnWkaE8VoquIGq33P7ib1ykxPYTLr0g',
    appId: '1:373667761246:ios:395b5adda9581e860278cf',
    messagingSenderId: '373667761246',
    projectId: 'lab3-mis-62c8f',
    storageBucket: 'lab3-mis-62c8f.firebasestorage.app',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcAnWkaE8VoquIGq33P7ib1ykxPYTLr0g',
    appId: '1:373667761246:ios:395b5adda9581e860278cf',
    messagingSenderId: '373667761246',
    projectId: 'lab3-mis-62c8f',
    storageBucket: 'lab3-mis-62c8f.firebasestorage.app',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADqvda68VWg-JymkKpE6wuJiCD6Avn0C4',
    appId: '1:373667761246:web:dc82bfa2322e25430278cf',
    messagingSenderId: '373667761246',
    projectId: 'lab3-mis-62c8f',
    authDomain: 'lab3-mis-62c8f.firebaseapp.com',
    storageBucket: 'lab3-mis-62c8f.firebasestorage.app',
    measurementId: 'G-4DKH73DGH9',
  );
}
